--CREACION DE PAQUETES PARA MANEJO DEL CARRITO
CREATE OR REPLACE PACKAGE PKG_CARRITO AS
PROCEDURE SP_GET_CARRITO_USUARIO (DATOS OUT SYS_REFCURSOR, VID IN NUMBER);
END;
   
CREATE OR REPLACE PACKAGE BODY PKG_CARRITO AS
 PROCEDURE SP_GET_CARRITO_USUARIO (DATOS OUT SYS_REFCURSOR, VID IN NUMBER)AS
BEGIN
    OPEN DATOS FOR
    SELECT I.ID_PRODUCTO, I.ID_ARTICULO, I.CANTIDAD, P.NOMBRE, P.PRECIO, (I.CANTIDAD*P.PRECIO) AS SUBTOTAL
    FROM ARTICULOS_CARRITO I
    INNER JOIN PRODUCTOS P
    ON I.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE I.ID_CARRITO = VID;
END SP_GET_CARRITO_USUARIO;

END;

INSERT INTO ARTICULOS_CARRITO VALUES (1, 1, 1, 2);
commit;