CREATE OR REPLACE PROCEDURE SP_OBTENER_PRODUCTOS_ACTIVOS (V_CURSOR OUT SYS_REFCURSOR)
IS
    V_CONTAR NUMBER;
BEGIN 
    SELECT COUNT(*) INTO V_CONTAR FROM PRODUCTOS WHERE ID_ESTADO = 1;
    IF V_CONTAR > 0 THEN
    OPEN V_CURSOR FOR
    SELECT ID_PRODUCTO, CANTIDAD, PRECIO, ID_CATEGORIA, ID_ESTADO, DESCRIPCION, NOMBRE, IMAGEN
    FROM PRODUCTOS WHERE ID_ESTADO = 1;
    
    ELSE
    OPEN V_CURSOR FOR
    SELECT 'No hay productos registrados' AS MENSAJE, NULL AS ID_PRODUCTO,  NULL AS CANTIDAD, NULL AS PRECIO, NULL AS ID_CATEGORIA, NULL AS ID_ESTADO, NULL AS DESCRIPCION, NULL AS NOMBRE
    FROM DUAL;
    END IF;
END;

COMMIT;

INSERT INTO CATEGORIAS_PRODUCTOS VALUES (1, 'REPOSTERIA', 1);

INSERT INTO PRODUCTOS VALUES (1, 20, 2000, 1, 1, 'Delicioso tamal de quesocrema', 'Tamal de Queso Crema') 

commit;

CREATE OR REPLACE PROCEDURE SP_OBTENER_PRODUCTO_POR_ID (V_CURSOR OUT SYS_REFCURSOR, V_ID IN NUMBER)
IS
BEGIN
    OPEN V_CURSOR FOR
    SELECT ID_PRODUCTO, CANTIDAD, PRECIO, ID_CATEGORIA, ID_ESTADO, DESCRIPCION, NOMBRE, IMAGEN
    FROM PRODUCTOS WHERE ID_PRODUCTO = V_ID;
END;
COMMIT;
